name: conpassione/litterlist
typeName: litterlist
group: kennel
prefixFields: false

fields:
  - identifier: conpassione/Header
    type: Basic
  - identifier: l_type
    type: Radio
    default: 1
    items:
      - label: 'Deckmeldung'
        value: 1
      - label: 'Wurfmeldung'
        value: 2
  - identifier: l_page
    type: Select
    renderType: selectSingle
    minitems: 1
    maxitems: 1
    foreign_table: pages
    foreign_table_where: 'AND pages.module="litter" ORDER BY pages.title'
