name: conpassione/licensdoglist
typeName: licensdoglist
group: kennel
prefixFields: false

fields:
  - identifier: conpassione/Header
    type: Basic
  - identifier: l_page
    type: Select
    renderType: selectSingle
    minitems: 1
    maxitems: 1
    foreign_table: pages
    foreign_table_where: 'AND pages.module="pedigree" ORDER BY pages.title'
