name: conpassione/kennel
typeName: conpassione-kennel
title: 'Kennel'
group: csbp
table: tx_cpkm_domain_model_kennel
languageAware: false
labelField:
  - k_name
  - k_last_name
  - k_first_name
sortField:
  - identifier: k_name
    order: asc
  - identifier: k_last_name
    order: asc
security:
  ignorePageTypeRestriction: true
prefixFields: false
fields:
  - identifier: p_kennel
    type: Palette
    fields:
    - identifier: k_name
      type: Text
      required: true
      size: 30
    - identifier: k_status
      type: Checkbox
      default: 0
      items:
        - label: aktiv?
    - identifier: k_show
      type: Checkbox
      default: 0
      items:
        - label: anzeigen?
    - identifier: k_variety
      type: Checkbox
      cols: 1
      default: 0
      items:
        - label: '---'
          value: 1
        - label: 'Museau Normal'
          value: 2
        - label: 'Face Rase'
          value: 4
  - identifier: p_breeder
    type: Palette
    description: Adresse der Zuchtstätte
    fields:
    - identifier: k_first_name
      type: Text
      size: 20
    - identifier: k_last_name
      type: Text
      size: 20
    - type: Linebreak
    - identifier: k_address
      type:  Textarea
      size: 30
      rows: 5
    - type: Linebreak
    - identifier: k_phone
      type: Text
      size: 20
    - identifier: k_mobile
      type: Text
      size: 20
    - type: Linebreak
    - identifier: k_email
      type: Text
      size: 20
    - identifier: k_web
      type: Text
      size: 20
