name: conpassione/event
typeName: conpassione-event
title: 'Event'
group: default
table: tx_cpkm_domain_model_event
languageAware: true
labelField:
  - e_date
  - e_title
  - e_place
sortField:
  - identifier: e_date
    order: desc
  - identifier: e_title
    order: asc
security:
  ignorePageTypeRestriction: true
prefixFields: false
fields:
  - identifier: e_title
    type: Text
    required: true
    size: 30
  - identifier: e_date
    type: DateTime
    format: date
    dbType: date
    disableAgeDisplay: true
    required: true
  - identifier: e_place
    type: Text
    size: 30
  - identifier: e_description
    type: Textarea
    rows: 5
    enableRichtext: true

