identifier: membership-application
label: newFormTemplates.MembershipApplicationForm.label
type: Form
prototypeName: standard
renderingOptions:
  submitButtonLabel: Absenden
finishers:
  - identifier: EmailToSender
    options:
      subject: 'Beantragung Mitgliedschaft'
      recipients:
        info@csbp.ch: 'Club Suisse du Berger des Pyrénées'
      senderAddress: '{email}'
      senderName: '{lastname}  {firstname}'
      addHtmlPart: true
      attachUploads: false
      title: 'Beantragung Mitgliedschaft für den Club Suisse du Berger des Pyrénées für  {firstname} {lastname}'
  - identifier: EmailToReceiver
    options:
      subject: Mitgliedschaftsantrag
      recipients:
        info@csbp.ch: CSBP
      senderAddress: '{email}'
      senderName: '{lastname}  {firstname}'
      addHtmlPart: true
      attachUploads: false
      translation:
        language: Standard
      title: ''
  - identifier: Confirmation
    options:
      message: 'Besten Dank für Ihre Anmeldung.'
      contentElementUid: ''

renderables:
  - renderingOptions:
      previousButtonLabel: 'Vorherige Seite'
      nextButtonLabel: 'Nächster Schritt'
    type: Page
    identifier: page-1
    label: Hauptmitglied
    renderables:
      - properties:
          options:
            - '---'
            - Herr
            - Frau
          elementDescription: 'Bitte Anrede wählen'
        identifier: salutation
        type: SingleSelect
        label: Anrede
        defaultValue: 0
      - type: GridRow
        identifier: gridrow-2
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            type: Text
            identifier: lastname
            label: Name
            properties:
              elementDescription: 'Nachname des Mitgliedes'
              fluidAdditionalAttributes:
                required: required
                minlength: '5'
                maxlength: '100'
                placeholder: Nachname
              validationErrorMessages:
                - code: 1238110957
                  message: 'Bitte Name erfassen'
            validators:
              - identifier: NotEmpty
              - options:
                  minimum: '5'
                  maximum: '100'
                identifier: StringLength
          - defaultValue: ''
            type: Text
            identifier: firstname
            label: Vorname
            properties:
              elementDescription: 'Vorname des Mitgliedes'
              fluidAdditionalAttributes:
                required: required
                minlength: '1'
                maxlength: '100'
                placeholder: Vorname
              validationErrorMessages:
                - code: 1221560910
                  message: 'Bitte Vorname ausfüllen'
            validators:
              - identifier: NotEmpty
              - options:
                  minimum: '1'
                  maximum: '100'
                identifier: StringLength
      - defaultValue: ''
        type: Textarea
        identifier: address
        label: Adresse
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Strasse und Nr'
      - type: GridRow
        identifier: gridrow-3
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            identifier: zipcode
            type: Text
            label: PLZ
            properties:
              fluidAdditionalAttributes:
                placeholder: PLZ
              elementDescription: Postleitzahl
          - defaultValue: ''
            identifier: city
            type: Text
            label: Ort
            properties:
              fluidAdditionalAttributes:
                placeholder: Wohnhort
      - type: GridRow
        identifier: gridrow-4
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            type: Text
            identifier: mobile
            label: Mobile
            properties:
              elementDescription: ''
              fluidAdditionalAttributes:
                placeholder: '079 000 00 00'
                required: required
                minlength: '10'
                maxlength: '25'
              validationErrorMessages:
                - code: 1238110957
                  message: 'Vollständige Telefonnummer erfassen'
            validators:
              - identifier: NotEmpty
              - options:
                  minimum: '10'
                  maximum: '25'
                identifier: StringLength
          - defaultValue: ''
            type: Email
            identifier: email
            label: E-Mail
            properties:
              fluidAdditionalAttributes:
                placeholder: email@madomain.ch
                required: required
                autocomplete: email
              validationErrorMessages:
                - code: 1221560910
                  message: 'Bitte E-Mail Adresse erfassen'
                - code: 1221559976
                  message: 'Die E-Mail ist für die Kommunikation nötig'
              elementDescription: 'Die E-Mail Adresse wird für die Kommunikation benötigt.'
            validators:
              - identifier: EmailAddress
              - identifier: NotEmpty
  - renderingOptions:
      previousButtonLabel: 'Vorherige Seite'
      nextButtonLabel: 'Nächster Schritt'
    type: Page
    identifier: page-2
    label: Parftnermitglied
    renderables:
      - type: GridRow
        identifier: gridrow-21
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            type: Text
            identifier: lastname2
            label: Name Partner
            properties:
              elementDescription: 'Name des Partnermitgliedes'
          - defaultValue: ''
            type: Text
            identifier: firstname2
            label: Vorname Partner
            properties:
              elementDescription: 'Vorname des Partnermitgliedes'
      - type: GridRow
        identifier: gridrow-24
        label: 'Grid: Zeile'
        renderables:
          - defaultValue: ''
            type: Text
            identifier: mobile2
            label: Mobile Partner
            properties:
              elementDescription: ''
              fluidAdditionalAttributes:
                placeholder: '079 000 00 00'
          - defaultValue: ''
            type: Email
            identifier: email2
            label: E-Mail Partner
            properties:
              fluidAdditionalAttributes:
                placeholder: email@madomain.ch
            validators:
              - identifier: EmailAddress
      - properties:
          text: 'Die folgenden Angaben werden benötigt um Sie als Clubmitglied mit den korrekten Informationen zu beliefern'
        type: StaticText
        identifier: statictext-1
        label: Zusatzinformationen
      - type: Checkbox
        identifier: confirmation
        label: 'Ich bin einverstanden, dass die erfassten Daten für die Zwecke des Club verwendet und im Mitgliederverzeichnis der SKG aufgeführt werden.'
        properties:
          elementDescription: ''
          fluidAdditionalAttributes:
            required: required
          validationErrorMessages:
            - code: 1221560910
              message: 'Bitte Verwendung der Daten zustimmen'
        validators:
          - identifier: NotEmpty
      - type: GridRow
        identifier: gridrow-1
        label: 'Grid: Zeile'
        renderables:
          - properties:
              options:
                deutsch: deutsch
                francais: français
              elementDescription: 'Wählen Sie die Korresponenzsprache aus'
              fluidAdditionalAttributes:
                required: required
            type: RadioButton
            identifier: comlanguage
            label: Korrespondenzsprache
            defaultValue: deutsch
            validators:
              - identifier: NotEmpty
          - properties:
              options:
                'Schweizer HUND': 'Schweizer HUND'
                'Cynologie Romand': 'Cynologie Romand'
                'Abo über anderen Verein': 'Abo über andern Verein'
              elementDescription: 'Wählen Sie die offizielle Zeitschrift aus'
              fluidAdditionalAttributes:
                required: required
            type: RadioButton
            identifier: officialpaper
            label: 'Offizielle Zeitschrift'
            defaultValue: 'Schweizer HUND'
            validators:
              - identifier: NotEmpty
  - renderingOptions:
      previousButtonLabel: 'Vorherige Seite'
      nextButtonLabel: 'Nächster Schritt'
    type: SummaryPage
    identifier: summarypage-1
    label: Zusammenfassung
