name: conpassione/eventlist
typeName: eventlist
group: z-cpextensions
prefixFields: false

fields:
  - identifier: conpassione/Header
    type: Basic
  - identifier: l_page
    type: Select
    renderType: selectSingle
    minitems: 0
    maxitems: 1
    foreign_table: pages
    foreign_table_where: 'AND pages.module="event" ORDER BY pages.title'
  - identifier: pages
    useExistingField: true
